### ISSUE TITLE
Saronite Animus.

### ISSUE THREAD

**Issue by Ulduar** [ACID-Scripts/WOTLK#22]
http://www.wowwiki.com/Saronite_Animus?file=Saronite_Animus.jpg
http://www.wowhead.com/npc=33524/saronite-animus#screenshots:id=131737
http://www.wowhead.com/npc=33524/saronite-animus
On spawn should cast unknown aura(like priest shadowform, see picture)

**Comment by xfurry** [comment]
I need to double check the sniff for this.
As far as I remember there is no shadowform aura or something like this. What you see in the pictures comes directly from the creature model.

**Comment by Ulduar** [comment]
Also Animus the summoned should be activated only after 2-3 seconds after summon - can be done in eventAI(SET_REACT_STATE PASSIVE) A lot of NPC have a delay - examples of the sea.

**Comment by xfurry** [comment]
Let's stop trying to replicate blizz in each and every way.

I agree that we need to be able to handle a REACT_STATE_PASSIVE, DEFENSIVE or ACTIVE but I think that as a general rule all the summoned creatures have a delay of 2-3 seconds before attacking.
So we need to do this in the core.

I don't know why are you bothered so much about such a minor things. There are tons of other major bugs or missing features that are required in core / scripts.

**Comment by Schmoozerd** [comment]
i think patman worked ages ago on something like this. Aside from code-issues (where put this in which way), there also was the more pressing details which npcs to not react in such a way.

**Comment by Ulduar** [comment]
I'll give you an example of Draenor (the last attempt) - Kargath Bladefist after death in Highmaul - Cho'gall appears, with its blue-skinned and cut out the guard, take him to the destination can not. But he does not attack us.
In the mythic mode, it is hostile to us, but do not kill the Emperor Mar'gok not attack us (but he was already in combat with us)

**Comment by xfurry** [comment]
1. Please don't give examples from Draenor. They probably don't apply to wotlk, not even to Cata.
2. Falric is scripted, and will behave as expected. Maybe all creatures that cast fear should take a break of 2-3 sec. We'll see when I get to him
3. You are right, the animus has this aura on spawn: 37816 - Shadowform. I will fix it.
4. For the react state I'll get back to you with a patch today or tomorrow. That will fix the Sunwell event and a lot of other things.
5. For the attack delay on spawn I think we still need that in core, and the patch from point 4 will help for this.

**Comment by Ulduar** [comment]
``` QUOTE
Please don't give examples from Draenor. They probably don't apply to wotlk, not even to Cata.
```
Once you said that examples of Cata are unacceptable (you talked about it on the forum) in any subject.
``` QUOTE
Falric is scripted, and will behave as expected. Maybe all creatures that cast fear should take a break of 2-3 sec. We'll see when I get to him
```
No, not all, does not have general Zaritrian. Falric should be delayed 2-3 seconds. In EventAI do not. And it should be.
``` QUOTE
For the react state I'll get back to you with a patch today or tomorrow. That will fix the Sunwell event and a lot of other things.
```
``` QUOTE
For the attack delay on spawn I think we still need that in core, and the patch from point 4 will help for this.
```
Do you want to hack the kernel? Are you sure that's wise?
What are some examples you either drive, you still are not satisfied. Having a functional SAI I would not even bother. Everything is there.

**Comment by Ulduar** [comment]
And in addition: you say that all beings have a delay.
You are absolutely in all NPC Classic, TBC, Wotlk, Cata, MoP and WoD investigated? Why such confidence?

**Comment by xfurry** [comment]
Please read again! ->
> Let's stop using the word "hack" in stupid ways. The things that we are developing here are not hacks, and this has to be clear to everyone! Some solutions are better than others, but there are no such things as hacks.


I'm not sure that ALL summoned npcs in classic, tbc and wotlk have the 2-3 sec passive delay when summoned.
But I know that many of them have this delay. We should open a separate discussion on this on the forum.
The delay after casting a fear spell is another generic thing, but I don't know how would that work in our core for the moment.

Now, let's stick to the topic. I'll fix the saronite animus missing auras and close this. For other topics, please open a new thread on the forum / github.
